return {
    "reskin_tool",
    "cookbook",
    "chestupgrade_stacksize,",
-- Traps/Mines
    "gunpowder",
    "beemine",
    "trap_teeth",
    "trap_bramble",
    "dug_trap_starfish",
    "sleepbomb",
    "panflute",
    "eyeturret_item",
    "cannonball_rock_item",
-- Healing
    "healingsalve",
    "bandage",
    "lifeinjector",
    "reviver",
    "compostwrap",
    "tillweedsalve",
    "bandage_butterflywings",
-- Celestial Portal
    "moonrockidol",
    "moonrockseed",
    "multiplayer_portal_moonrock_constr_plans",
-- Pearl Stuff
    "hermit_pearl",
    "hermit_cracked_pearl",
    "messagebottle",
    "messagebottleempty",
-- Character-Specific Items
    -- Wendy
        "abigail_flower",
        "ghostlyelixir_attack",
        "ghostlyelixir_speed",
        "ghostlyelixir_slowregen",
        "ghostlyelixir_fastregen",
        "ghostlyelixir_shield",
        "ghostlyelixir_retaliation",
        "ghostlyelixir_shadow",
        "ghostlyelixir_revive",
        "ghostlyelixir_shadow",
        "elixir_container",
        "graveurn",
    -- Willow
        "bernie_inactive",
    -- Wigfrid
        "battlesong_durability",
        "battlesong_healthgain",
        "battlesong_sanitygain",
        "battlesong_sanityaura",
        "battlesong_fireresistance",
        "battlesong_instant_taunt",
        "battlesong_instant_panic",
        "battlesong_instant_revive",
        "battlesong_lunaraligned",
        "battlesong_shadowaligned",
        "battlesong_container",
    -- Wes
        "balloons_empty",
    -- Wortox
        "wortox_soul",
    -- Wickerbottom
        "book_birds",
        "book_brimstone",
        "book_gardening",
        "book_horticulture",
        "book_horticulture_upgraded",
        "book_silviculture",
        "book_sleep",
        "book_tentacles", -- ( ͡° ͜ʖ ͡°) 
        "book_bees",
        "book_fire",
        "book_fish",
        "book_light",
        "book_light_upgraded",
        "book_moon",
        "book_rain",
        "book_research_station",
        "book_temperature",
        "book_web",
    -- Waxwell
        "waxwelljournal",
-- Moon Stuff
    "bathbomb",
    "singingshell_octave3",
    "singingshell_octave4",
    "singingshell_octave5",
-- Cave Stuff
    "atrium_key",
    "nightmare_timepiece",
    "archive_lockbox",
    "archive_resonator_item",
    "shadowheart",
-- Follower Items
    "lavae_tooth",
    "fruitflyfruit",
    "chester_eyebone",
    "hutch_fishbowl",
    "glommerflower",
    "thurible",
    "houndwhistle",
    "onemanband",
    "pig_coin",
    "beef_bell",
-- Statue Sketches
    "chesspiece_moosegoose_sketch",
    "chesspiece_dragonfly_sketch",
    "chesspiece_bearger_sketch",
    "chesspiece_deerclops_sketch",
    "chesspiece_crabking_sketch",
    "chesspiece_malbatross_sketch",
    "chesspiece_antlion_sketch",
    "chesspiece_beequeen_sketch",
    "chesspiece_klaus_sketch",
    "chesspiece_minotaur_sketch",
    "chesspiece_stalker_sketch",
    "chesspiece_toadstool_sketch",
    "chesspiece_knight_sketch",
    "chesspiece_bishop_sketch",
    "chesspiece_rook_sketch",
    "chesspiece_formal_sketch",
    "chesspiece_muse_sketch",
    "chesspiece_pawn_sketch",
    "chesspiece_anchor_sketch",
    "chesspiece_butterfly_sketch",
    "chesspiece_moon_sketch",
    "chesspiece_claywarg_sketch",
    "chesspiece_clayhound_sketch",
    "chesspiece_carrat_sketch",
    "chesspiece_beefalo_sketch",
-- Tackle Blueprints 
    "oceanfishinglure_hermit_drowsy_tacklesketch",
    "oceanfishinglure_hermit_heavy_tacklesketch",
    "oceanfishinglure_hermit_rain_tacklesketch",
    "oceanfishinglure_hermit_snow_tacklesketch",
    "oceanfishingbobber_ball_tacklesketch",
    "oceanfishingbobber_oval_tacklesketch",
    "oceanfishingbobber_crow_tacklesketch",
    "oceanfishingbobber_robin_tacklesketch",
    "oceanfishingbobber_robin_winter_tacklesketch",
    "oceanfishingbobber_canary_tacklesketch",
    "oceanfishingbobber_goose_tacklesketch",
    "oceanfishingbobber_malbatross_tacklesketch",
-- Special Events
    "firecrackers",
    -- Year of the Carrat
        "yotc_carrat_scale_item",
        "yotc_carrat_gym_speed_item",
        "yotc_carrat_gym_reaction_item",
        "yotc_carrat_gym_stamina_item",
        "yotc_carrat_gym_direction_item",
        "yotc_carrat_race_start_item",
        "yotc_carrat_race_checkpoint_item",
        "yotc_carrat_race_finish_item",
    -- Year of the Beefalo
        "yotb_pattern_fragment_1",
        "yotb_pattern_fragment_2",
        "yotb_pattern_fragment_3",
        "yotb_post_item",
        "yotb_sewingmachine_item",
        "yotb_stage_item",
        "beefalo_groomer_item",
    -- Hallowed Nights
        "halloweenpotion_bravery_small",
        "halloweenpotion_bravery_large",
        "halloweenpotion_health_small",
        "halloweenpotion_health_large",
        "halloweenpotion_sanity_small",
        "halloweenpotion_sanity_large",
        "halloweenpotion_embers",
        "halloweenpotion_sparks",
        "halloweenpotion_moon",
}
