return {
-- Meat
	"meat",
	"cookedmeat",
	"meat_dried",
	"monstermeat",
	"cookedmonstermeat",
	"monstermeat_dried",
	"smallmeat",
	"cookedsmallmeat",
	"smallmeat_dried",
	"drumstick",
	"drumstick_cooked",
	"froglegs",
	"froglegs_cooked",
-- Fish (Ponds)
	"pondfish",
	"fish",
	"fish_cooked",
	"pondeel",
	"eel",
	"eel_cooked",
-- Medium Fish (Ocean)
	"oceanfish_medium_1_inv",
	"oceanfish_medium_2_inv",
	"oceanfish_medium_3_inv",
	"oceanfish_medium_4_inv",
	"oceanfish_medium_5_inv",
	"oceanfish_medium_6_inv",
	"oceanfish_medium_7_inv",
	"oceanfish_medium_8_inv",
-- Small Fish (Ocean)
	"oceanfish_small_1_inv",
	"oceanfish_small_2_inv",
	"oceanfish_small_3_inv",
	"oceanfish_small_4_inv",
	"oceanfish_small_5_inv",
	"oceanfish_small_6_inv",
	"oceanfish_small_7_inv",
	"oceanfish_small_8_inv",
	"oceanfish_small_9_inv",
-- Fish Meat
	"fishmeat",
	"fishmeat_cooked",
	"fishmeat_small",
	"fishmeat_small_cooked",
-- Barnacles
	"barnacle",
	"barnacle_cooked",
-- Wobster
	"wobster_sheller_land",
	"wobster_sheller_dead",
	"wobster_sheller_dead_cooked",
-- Eggs
	"tallbirdegg",
	"tallbirdegg_cooked",
	"bird_egg",
	"bird_egg_cooked",
	"tallbirdegg_cracked",
-- Farm Foods
	-- Veggies
		"asparagus",
		"asparagus_cooked",
		"corn",
		"corn_cooked",
		"onion",
		"onion_cooked",
		"carrot",
		"carrot_cooked",
		"potato",
		"potato_cooked",
		"tomato",
		"tomato_cooked",
		"garlic",
		"garlic_cooked",
		"pumpkin",
		"pumpkin_cooked",
		"eggplant",
		"eggplant_cooked",
		"pepper",
		"pepper_cooked",
	-- Fruits
		"dragonfruit",
		"dragonfruit_cooked",
		"pomegranate",
		"pomegranate_cooked",
		"watermelon",
		"watermelon_cooked",
		"durian",
		"durian_cooked",
	-- Weeds
		"tillweed",
		"forgetmelots",
		"firenettles",
-- Mushrooms
	"red_cap",
	"red_cap_cooked",
	"green_cap",
	"green_cap_cooked",
	"blue_cap",
	"blue_cap_cooked",
	"moon_cap",
	"moon_cap_cooked",
-- Cactus
	"cactus_meat",
	"cactus_meat_cooked",
	"cactus_flower",
-- Moon Island Foods
	"cutlichen",
	"rock_avocado_fruit_ripe",
	"rock_avocado_fruit_ripe_cooked",
	"rock_avocado_fruit",
-- Fruits
	"berries",
	"berries_cooked",
	"berries_juicy",
	"berries_juicy_cooked",
	"cave_banana",
	"cave_banana_cooked",
	"wormlight",
	"wormlight_lesser",
-- Butterfly Wings
	"butterflywings",
	"moonbutterflywings",
-- Dairy
	"butter",
	"goatmilk",
-- Bees!
	"honey",
	"royal_jelly",
-- Acorn
	"acorn_cooked",
-- Ice
	"ice",
-- Inedible crockpot ingredients
	"mole",
	"twigs",
	"boneshard",
	"nightmarefuel",
	"lightninggoathorn",
-- Elephant Trunks
	"trunk_summer",
	"trunk_winter",
	"trunk_cooked",
-- Lure Plant
	"plantmeat",
	"plantmeat_cooked",
-- Bats
	"batwing",
	"batwing_cooked",
	"batnose",
	"batnose_cooked",
-- Long pig
	"humanmeat",
	"humanmeat_cooked",
	"humanmeat_dried",
-- Mandrake
	"cookedmandrake",
	"mandrake",
-- Flowers/Leaves
	"moon_tree_blossom",
	"petals",
	"petals_evil",
	"foliage",
	"succulent_picked",
	"lightbulb",
-- antchovies.
	"antchovies",
-- Seaweed
	"kelp",
	"kelp_cooked",
	"kelp_dried",
-- the slime
	"phlegm",
	"glommerfuel",
-- Boss Drops
	"minotaurhorn",
	"deerclops_eyeball",
-- Spoiled/Rotten Food
	"spoiled_food",
	"spoiled_fish",
	"spoiled_fish_small",
	"rottenegg",
-- Seeds
	"asparagus_seeds",
	"carrot_seeds",
	"corn_seeds",
	"eggplant_seeds",
	"garlic_seeds",
	"onion_seeds",
	"pepper_seeds",
	"potato_seeds",
	"pumpkin_seeds",
	"tomato_seeds",
	"dragonfruit_seeds",
	"durian_seeds",
	"pomegranate_seeds",
	"watermelon_seeds",
	"seeds",
	"seeds_cooked",
-- Spices
	"spice_sugar",
	"spice_salt",
	"spice_chili",
	"spice_garlic",
-- Woodie's Idols
	"wereitem_beaver",
	"wereitem_goose",
	"wereitem_moose",
-- Special Events
	-- Year of the Pig
		"yotp_food1",
		"yotp_food2",
		"yotp_food3",
	-- Winter's Feast
		"winter_food1",
		"winter_food2",
		"winter_food3",
		"winter_food4",
		"winter_food5",
		"winter_food6",
		"winter_food7",
		"winter_food8",
		"winter_food9",
		"wintersfeastfuel",
		"crumbs",
	-- Halloween Candy
		"halloweencandy_1",
		"halloweencandy_2",
		"halloweencandy_3",
		"halloweencandy_4",
		"halloweencandy_5",
		"halloweencandy_6",
		"halloweencandy_7",
		"halloweencandy_8",
		"halloweencandy_9",
		"halloweencandy_10",
		"halloweencandy_11",
		"halloweencandy_12",
		"halloweencandy_13",
		"halloweencandy_14",
}