return {
    -- Farm Seeds
    "asparagus_seeds",
    "carrot_seeds",
    "corn_seeds",
    "eggplant_seeds",
    "garlic_seeds",
    "onion_seeds",
    "pepper_seeds",
    "potato_seeds",
    "pumpkin_seeds",
    "tomato_seeds",
    "dragonfruit_seeds",
    "durian_seeds",
    "pomegranate_seeds",
    "watermelon_seeds",
    "seeds",
    -- Mushrooms and Spores
    "red_cap",
    "spore_medium",
    "green_cap",
    "spore_small",
    "blue_cap",
    "spore_tall",
    -- Lure plant
    "lureplantbulb",
    -- Trees
    "marblebean",
    "livingtree_root",
    "twiggy_nut",
    "acorn",
    "pinecone",
    "moonbutterfly",
    "acorn_sapling",
    -- Flowers
    "butterfly",
    "moonbutterfly",
    -- Dug crops
    "dug_berrybush",
    "dug_berrybush2",
    "dug_berrybush_juicy",
    "dug_grass",
    "dug_sapling",
    "dug_sapling_moon",
    "dug_marsh_bush",
    "dug_rock_avocado_bush",
    "rock_avocado_fruit_sprout",
    "bullkelp_root",
    "dug_bananabush",
    "dug_monkeytail",
    -- Barnacles
    "waterplant_planter",
    -- Ancient Trees
    "ancienttree_gem_sapling_item",
    "ancienttree_nightvision_sapling_item",
    "ancienttree_seed",
    -- Waxed Items
    "dug_sapling_waxed",
    "dug_sapling_moon_waxed",
    "dug_bananabush_waxed",
}
