return {
-- Melee Weapons
	"cane",
	"bullkelp_root",
	"whip",
	"spear",
	"spear_wathgrithr",
	"batbat",
	"trident",
	"tentaclespike",
	"hambat",
	"ruins_bat",
	"nightsword",
	"glasscutter",
	"nightstick",
	"cutless",
-- Ranged Weapons
	"boomerang",
	"blowdart_pipe",
	"blowdart_yellow",
	"blowdart_sleep",
	"blowdart_fire",
	"staff_tornado",
	"waterplant_bomb",
	"bomb_lunarplant",

-- Wes
	"balloonvest",
	"balloonhat",
	"balloonspeed",
	"balloonparty",
	"balloon",
-- Walter
	"slingshot",
	"slingshotammo_rock",
	"slingshotammo_gold",
	"slingshotammo_marble",
	"slingshotammo_poop",
	"slingshotammo_freeze",
	"slingshotammo_slow",
	"slingshotammo_thulecite",
-- Wolfgang
	"dumbell",
	"dumbell_bluegem",
	"dumbell_redgem",
	"dumbell_gem",
	"dumbell_golden",
	"dumbell_heat",
	"dumbell_marble",
-- Wendy
	"ghostflowerhat",

-- Armor Pairs

-- Armor (Head Slot)
	"cookiecutterhat",
	"footballhat",
	"wathgrithrhat",
	"beehat",
	"ruinshat",
	"slurtlehat",
	"hivehat",
	"skeletonhat",
	"dreadstonehat",
-- Armor (Body Slot)
	"armorgrass",
	"armor_bramble",
	"armorwood",
	"armorruins",
	"armor_sanity",
	"armormarble",
	"armorsnurtleshell",
	"armordragonfly",
	"armorskeleton",
	"armor_lunarplant",
	"armor_lunarplant_husk",
	"armor_voidcloth",
	"armordreadstone",
	"armorwagpunk",
-- Backpacks
	"backpack",
	"piggyback",
	"krampus_sack",
	"spicepack",
	"icepack",
	"candybag",
	"seedpouch",
	"beargerfur_sack",
-- Misc.
	"diviningrod", -- you will never be free
}
